### ISSUE TITLE
Initial received Websocket data from Query API is not confom to the documentation

### ISSUE THREAD

**Issue by mgratzke** [bbc/nmos-query#4]
After subscribing to the Query API the nmos client gets an initial update from the Query API instance. The received data is not conform to the [documentation](https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/4.2.%20Behaviour%20-%20Querying.md) since this initial data has no valid "topic" value for the "grain" object. (It is "//" for all grains instead  e.g. "/senders/).

After this initial transfer the further recived event-based updates are correct.

**Comment by simonrankine** [comment]
I'm afraid I'm struggling to reproduce this, could you post the JSON your sending to the subscription endpoint please? It probably only shows up for certian "params" entries.

**Comment by mgratzke** [comment]
Dear Simon,

this is my reqest:

` {
   "max_update_rate_ms" : 100,
   "params" : {
      "label" : "AES67-1 (NMOSTES.Device_1.WCWB"
   },
   "persist" : false,
   "resource_path" : "/senders",
   "secure" : false
}
`

and this is what i get as first response via websocket (excerpt):

{
   "creation_timestamp" : "0:0",
   "duration" : {
      "denominator" : 1,
      "numerator" : 0
   },
   "flow_id" : "76ae67c1-a505-4802-a8a1-6f46ee45b6ee",
   "grain" : {
      "data" : [ /* removed in this example, lists device */ .. ]
      "topic" : "//", /* */ 
      "type" : "urn:x-nmos:format:data.event"
   },
   "grain_type" : "event",
   "origin_timestamp" : "0:0",
   "rate" : {
      "denominator" : 1,
      "numerator" : 0
   },
   "source_id" : "4744db6c-49da-3017-bcc7-9d61fd173d2f",
   "sync_timestamp" : "0:0"
}

**Comment by simonrankine** [comment]
Thank you, I shall investigate and let you know how I get on.

**Comment by simonrankine** [comment]
Hi,

I've tried to re-create the problem with the request you provided, and the response I got from the query API on opening the websocket was as follows:

{  
   "duration":{  
      "denominator":1,
      "numerator":0
   },
   "rate":{  
      "denominator":1,
      "numerator":0
   },
   "grain":{  
      "topic":"/senders/",
      "data":[  

      ],
      "type":"urn:x-nmos:format:data.event"
   },
   "flow_id":"a59b4cda-888e-4cd6-bba1-bcd1e146543f",
   "source_id":"0cb82774-2976-371c-ab7a-82982a5cbee7",
   "sync_timestamp":"0:0",
   "origin_timestamp":"0:0",
   "creation_timestamp":"0:0",
   "grain_type":"event"
}

so there is something else going on here.

The offending code is likely to be in the do_sup method in common/query.py. This would explain why the bug only occours initially, as this method is only used for the first response - subsequently do_sync is used instead.

My suggestion would be to try putting in a few print statements round that method and see where the topic is getting lost, especially around lines 222, 230 and 231 then run the query API manually from the command line and see what you get.

Sorry I can't be of more help - quite hard to debug without being able to reproduce the issue.

**Comment by mgratzke** [comment]
Thank you Simon for your investigation. I will follow your suggestion later, for now i have other things that need my attention.

Can we in get in contact beside github? I work for a company that provides hardware/software to your company and there may come up some more questions about your planned NMOS installation.

**Comment by simonrankine** [comment]
No problem, glad I was able to help.

You are welcome to contact me at Simon.Rankine@bbc.co.uk, although I am not directly involved in the design of BBC facilities as I am an R&D engineer working on new specifications and standards.

If you are not already I would encourage you to consider becoming involved in the AMWA incubator - this organises workshops for interoperability of the NMOS specifications and also provides support to those implementing them. https://www.nmos.tv/about_NMI.html

**Comment by mgratzke** [comment]
Ok, i've invested some more time today and found the problem. My posted subscription request data was packed into a "data" object:

`
{
    data : {
        resource_path" : ..."
        ....
    }
}
`
instead 
`
{
        resource_path" : ..."
        ....
}
`

Anyway. Wireshark shows that the server accepted that request and responded with  HTTP/1.1 201 CREATED. After that the recieved data had no valid topic.

With the correct subscription request the response is  HTTP/1.1 200 OK and the topic in the grain is set correctly.

**Comment by simonrankine** [comment]
Excellent - thanks for letting me know. Should probably respond with a 400 if you send it that - I'll look into it. I'll close this for now anyway.
